--Sentencias CREATE TABLE

CREATE TABLE CLIENTE (
IDCLIENTE NUMBER(10,0) NOT NULL, --cantidad de digitos, decimales primary key
FKCOTIZACION1 NUMBER(10,0) NOT NULL,
FKFOLIO1 NUMBER(10,0) NOT NULL,
NOMBRE VARCHAR2(20) NOT NULL,
APPPATERNO VARCHAR2(20) NOT NULL,
APPMATERNO VARCHAR2(20),
EMAIL VARCHAR2(50) NOT NULL,
RFC VARCHAR2(13) NOT NULL,
DIRECCION VARCHAR2(50) NOT NULL,
TELEFONO NUMBER(10,0) NOT NULL
);

CREATE TABLE COTIZACION(
IDCOTIZACION NUMBER(10,0) NOT NULL, --primary key
FKCLIENTE1 NUMBER(10,0) NOT NULL,
FKFOLIO2 NUMBER(10,0) NOT NULL,
FKMARCA1 NUMBER(10,0) NOT NULL,
FKMODELOAUTO1 NUMBER(10,0) NOT NULL,
FKTIPOSEGURO2 NUMBER(10,0) NOT NULL,
FKESTADO2 NUMBER(10,0) NOT NULL,
FKTABULADOR1 NUMBER(10,0) NOT NULL,
FECHACOTIZACION DATE,
ANIOAUTO NUMBER(4,0),
CODIGOPOSTAL NUMBER(5,0),
EDADCONDUCTOR NUMBER(2,0),
FECHANACIMIENTO DATE
);

CREATE TABLE TABULADOR(
IDTABULADOR NUMBER(10,0) NOT NULL,
FKCOTIZACION4 NUMBER(10,0) NOT NULL,
FKMARCA2 NUMBER(10,0) NOT NULL,
FKMODELOAUTO2 NUMBER(10,0) NOT NULL,
FKTIPOSEGURO1 NUMBER(10,0) NOT NULL,
FKESTADO1 NUMBER(10,0) NOT NULL,
COSTOANUAL NUMBER(7,3)
);

CREATE TABLE POLIZA(
FOLIO NUMBER(10,0) NOT NULL,
FKCLIENTE2 NUMBER(10,0) NOT NULL,
FKPOLIZAANTERIOR NUMBER(10,0) NULL,
FKCOTIZACION7 NUMBER(10,0) NOT NULL,
FKPAGOSEGURO NUMBER(10,0) NOT NULL,
FKSINIESTRO1 NUMBER(10,0) NOT NULL,
FECHAINICIO DATE,
HORAINICIO NUMBER(2,0),
FECHAFIN DATE,
PLACA VARCHAR(10) NOT NULL,
NUMEROSERIEAUTO NUMBER(20) NOT NULL
);

CREATE TABLE PAGOSEGURO(
IDPAGOSEGURO NUMBER(10,0) NOT NULL,
FKFOLIO3 NUMBER(10,0) NOT NULL,
NUMEROTARJETA NUMBER(10,0) NOT NULL,
TIPOTARJETA VARCHAR2(20) NOT NULL,
MES VARCHAR(10),
ANIOEXPIRACION  NUMBER(4,0),
NUMEROSEGURIDAD NUMBER(10,0)
);

CREATE TABLE CATALOGO(
IDCATALOGO NUMBER(10,0) NOT NULL,
FKMARCA3 NUMBER(10,0) NOT NULL,
FKMODELOAUTO3 NUMBER(10,0) NOT NULL,
FKTIPOSEGURO3 NUMBER(10,0) NOT NULL,
FKESTADO3 NUMBER(10,0) NOT NULL,
FKASEGURADORA1 NUMBER(10,0) NOT NULL,
TIPOCATALOGO VARCHAR2(10)
);

CREATE TABLE ASEGURADORA(
IDASEGURADORA NUMBER(10,0) NOT NULL,
FKCATALOGO5 NUMBER(10,0) NOT NULL,
FKAUTOINVOLUCRADO3 NUMBER(10,0) NOT NULL,
DESCRIPCION VARCHAR2(100)
);

CREATE TABLE MARCAAUTO(
IDMARCA NUMBER(10,0) NOT NULL,
FKCATALOGO1 NUMBER(10,0) NOT NULL,
FKCOTIZACION2 NUMBER(10,0) NOT NULL,
FKTABULADOR2 NUMBER(10,0) NOT NULL,
DESCRIPCION VARCHAR2(100)
);

CREATE TABLE MODELOAUTO(
IDMODELOAUTO NUMBER(10,0) NOT NULL,
FKCATALOGO2 NUMBER(10,0) NOT NULL,
FKCOTIZACION3 NUMBER(10,0) NOT NULL,
FKTABULADOR3 NUMBER(10,0) NOT NULL,
DESCRIPCION VARCHAR2(100)
);
tereghraetjsryrmtnrshgehr<jty
CREATE TABLE ESTADO(
IDESTADO NUMBER(10,0) NOT NULL,
FKCATALOGO4 NUMBER(10,0) NOT NULL,
FKCOTIZACION6 NUMBER(10,0) NOT NULL,
FKTABULADOR5 NUMBER(10,0) NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE TIPOSEGURO(
IDTIPOSEGURO NUMBER(10,0) NOT NULL,
FKCATALOGO3 NUMBER(10,0) NOT NULL,
FKCOTIZACION5 NUMBER(10,0) NOT NULL,
FKTABULADOR4 NUMBER(10,0) NOT NULL,
DESCRIPCION VARCHAR2(100)
);

CREATE TABLE SINIESTRO(
IDSINIESTRO NUMBER(10,0) NOT NULL,
FKFOLIO4 NUMBER(10,0) NOT NULL,
FKSOCIAL1  NUMBER(10,0) NOT NULL,
FKCOLISION1 NUMBER(10,0) NOT NULL,
FKMATERIAL1 NUMBER(10,0)  NOT NULL,
FECHA DATE,
HORA NUMBER(2,0),
DIRECCION VARCHAR(50) NOT NULL,
 --FLAG , NO HAY BOOLEAN , SE IMPLEMENTA CON Y / N, REVISAR
TIPOCOLISION CHAR(1) DEFAULT 'F' CHECK ((TIPOCOLISION = 'T') OR (TIPOCOLISION = 'F')) NOT NULL,
TIPOMATERIAL CHAR(1) DEFAULT 'F' CHECK ((TIPOMATERIAL = 'T') OR (TIPOMATERIAL = 'F')) NOT NULL,
TIPOSOCIAL CHAR(1) DEFAULT 'F' CHECK ((TIPOSOCIAL = 'T') OR (TIPOSOCIAL = 'F')) NOT NULL,
FOTO BLOB
);

CREATE TABLE COLISION(
IDCOLISION NUMBER(10,0) NOT NULL,
FKSINIESTRO2 NUMBER(10,0) NOT NULL,
FKAUTOINVOLUCRADO1 NUMBER(10,0) NOT NULL,
NUMEROREPORTEVIAL NUMBER(20,0),
REQUIEREGRUA CHAR(1) DEFAULT 'F' CHECK ((REQUIEREGRUA = 'T') OR (REQUIEREGRUA = 'F')) NOT NULL
);

CREATE TABLE AUTOINVOLUCRADO(
IDAUTOINVOLUCRADO NUMBER(10,0) NOT NULL,
FKASEGURADORA2 NUMBER(10,0) NOT NULL,
FKCOLISION2 NUMBER(10,0) NOT NULL,
FKMATERIAL3 NUMBER(10,0)  NOT NULL,
MARCAINV VARCHAR2(20) NOT NULL,
MODELOINV VARCHAR(20) NOT NULL,
NUMEROSERIEINV NUMBER(20) NOT NULL,
NUMEROPOLIZAINV(20)
);

CREATE TABLE MATERIAL(
IDMATERIAL NUMBER(10,0)  NOT NULL,
FKSINIESTRO3 NUMBER(10,0) NOT NULL,
FKPERSONAAFECTADA2 NUMBER(10,1) NOT NULL,
FKAUTOINVOLUCRADO2 NUMBER(10,0) NOT NULL,
DESCRIPCION VARCHAR(200),
FOTO BLOB
);

CREATE TABLE SOCIAL(
IDSOCIAL  NUMBER(10,0) NOT NULL,
FKSINIESTRO4 NUMBER(10,0) NOT NULL,
FKPERSONAAFECTADA1 NUMBER(10,1) NOT NULL,
REQUIEREAMBULANCIA CHAR(1) DEFAULT 'F' CHECK ((REQUIEREAMBULANCIA = 'T') OR (REQUIEREAMBULANCIA = 'F')) NOT NULL,
NOMBREHOSPITAL VARCHAR2(30),
DIRECCIONHOSPITAL VARCHAR2(30)
);

CREATE TABLE PERSONAAFECTADA(
IDPERSONAAFECTADA NUMBER(10,1) NOT NULL,
FKSOCIAL2  NUMBER(10,0) NOT NULL,
FKMATERIAL2 NUMBER(10,0)  NOT NULL,
NOMBRECOMPLETO VARCHAR2(45) NOT NULL,
CURP VARCHAR2(20) NOT NULL,
DESCRIPCION VARCHAR2 (200)
);

-- Sentencias ALTER TABLE

ALTER TABLE CLIENTE ADD
  CONSTRAINT PKCLIENTE
  PRIMARY KEY (IDCLIENTE);

ALTER TABLE CLIENTE ADD
  CONSTRAINT FKCOTIZACION1
  FOREIGN KEY (IDCOTIZACION)
  REFERENCES COTIZACION(IDCOTIZACION);

ALTER TABLE CLIENTE ADD
  CONSTRAINT FKFOLIO1
  FOREIGN KEY (FOLIO)
  REFERENCES POLIZA(FOLIO);

ALTER TABLE CLIENTE ADD
  CONSTRAINT NOTREPEEMAIL UNIQUE (EMAIL);

ALTER TABLE CLIENTE ADD
  CONSTRAINT NOTREPEFRC UNIQUE (RFC);

ALTER TABLE CLIENTE ADD
  CONSTRAINT NOTREPETEL UNIQUE (TELEFONO);



ALTER TABLE COTIZACION ADD
  CONSTRAINT IDCOTIZACION
  PRIMARY KEY(IDCOTIZACION);

ALTER TABLE COTIZACION ADD
  CONSTRAINT FKCLIENTE1
  FOREIGN KEY(FKCLIENTE1)
  REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE COTIZACION ADD
  CONSTRAINT FKFOLIO2
  FOREIGN KEY(FKFOLIO2)
  REFERENCES POLIZA(FOLIO);

ALTER TABLE COTIZACION ADD
  CONSTRAINT FKMARCA1
  FOREIGN KEY (FKMARCA1)
  REFERENCES MARCA(IDMARCA);

ALTER TABLE COTIZACION ADD
  CONSTRAINT FKMODELOAUTO1
  FOREIGN KEY (FKMODELOAUTO1)
  REFERENCES MODELOAUTO(IDMODELOAUTO);

ALTER TABLE COTIZACION ADD
  CONSTRAINT FKTIPOSEGURO2
  FOREIGN KEY (FKTIPOSEGURO2)
  REFERENCES TIPOSEGURO(IDTIPOSEGURO);

ALTER TABLE COTIZACION ADD
  CONSTRAINT FKESTADO2
  FOREIGN KEY (FKESTADO2)
  REFERENCES ESTADO(IDESTADO);

ALTER TABLE TABULADOR ADD
  CONSTRAINT FKTABULADOR1
  FOREIGN KEY (FKTABULADOR1)
  REFERENCES TABULADOR(IDTABULADOR);



ALTER TABLE TABULADOR ADD
  CONSTRAINT IDTABULADOR
  PRIMARY KEY (IDTABULADOR);

ALTER TABLE TABULADOR ADD
  CONSTRAINT FKCOTIZACION4
  FOREIGN KEY (FKCOTIZACION4)
  REFERENCES COTIZACION(IDCOTIZACION);

ALTER TABLE TABULADOR ADD
  CONSTRAINT FKMARCA2
  FOREIGN KEY (FKMARCA2)
  REFERENCES MARCAAUTO(IDMARCA);

ALTER TABLE TABULADOR ADD
  CONSTRAINT FKMODELOAUTO2
  FOREIGN KEY (FKMODELOAUTO2)
  REFERENCES MODELOAUTO(IDMODELOAUTO);

ALTER TABLE TABULADOR ADD
  CONSTRAINT FKTIPOSEGURO1
  FOREIGN KEY (FKTIPOSEGURO1)
  REFERENCES TIPOSEGURO(IDTIPOSEGURO);

ALTER TABLE TABULADOR ADD
  CONSTRAINT FKESTADO
  FOREIGN KEY (IDESTADO)
  REFERENCES ESTADO(IDESTADO);

ALTER TABLE TABULADOR ADD
  CONSTRAINT COSTOANUAL
  CHECK(COSTOANUAL>=10000);



ALTER TABLE POLIZA ADD
  CONSTRAINT FOLIO
  PRIMARY KEY (FOLIO);

ALTER TABLE POLIZA ADD
  CONSTRAINT FKCLIENTE2
  FOREIGN KEY(FKCLIENTE2)
  REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE POLIZA ADD
  CONSTRAINT FKPOLIZAANTERIOR
  FOREIGN KEY (FKPOLIZAANTERIOR)
  REFERENCES POLIZA (FOLIO);

ALTER TABLE POLIZA ADD
  CONSTRAINT FKCOTIZACION7
  FOREIGN KEY (FKCOTIZACION7)
  REFERENCES COTIZACION (IDCOTIZACION);

ALTER TABLE POLIZA ADD
  CONSTRAINT FKPAGOSEGURO
  FOREIGN KEY (FKPAGOSEGURO)
  REFERENCES PAGOSEGURO(IDPAGOSEGURO);

ALTER TABLE POLIZA ADD
  CONSTRAINT FKSINIESTRO1
  FOREIGN KEY(FKSINIESTRO1)
  REFERENCES SINIESTRO(IDSINIESTRO);



ALTER TABLE PAGOSEGURO ADD
  CONSTRAINT IDPAGOSEGURO
  PRIMARY KEY(IDPAGOSEGURO);

ALTER TABLE PAGOSEGURO ADD
  CONSTRAINT FKFOLIO3
  FOREIGN KEY (FKFOLIO3)
  REFERENCES POLIZA(FOLIO);



ALTER TABLE CATALOGO ADD
  CONSTRAINT IDCATALOGO
  PRIMARY KEY (IDCATALOGO);

ALTER TABLE CATALOGO ADD
  CONSTRAINT FKMARCA3
  FOREIGN KEY (FKMARCA3)
  REFERENCES MARCAAUTO(IDMARCA);

ALTER TABLE CATALOGO ADD
  CONSTRAINT FKMODELOAUTO3
  FOREIGN KEY (FKMODELOAUTO3)
  REFERENCES MODELOAUTO(IDMODELOAUTO);

ALTER TABLE CATALOGO ADD
  CONSTRAINT FKTIPOSEGURO3
  FOREIGN KEY (FKTIPOSEGURO3)
  REFERENCES TIPOSEGURO(IDTIPOSEGURO);

ALTER TABLE CATALOGO ADD
  CONSTRAINT FKESTADO3
  FOREIGN KEY (FKESTADO3)
  REFERENCES ESTADO(IDESTADO);

ALTER TABLE CATALOGO ADD
  CONSTRAINT FKASEGURADORA1
  FOREIGN KEY (FKASEGURADORA1)
  REFERENCES ASEGURADORA(IDASEGURADORA);



ALTER TABLE ASEGURADORA ADD
  CONSTRAINT IDASEGURADORA
  PRIMARY KEY(IDASEGURADORA);

ALTER TABLE ASEGURADORA ADD
  CONSTRAINT FKCATALOGO5
  FOREIGN KEY (FKCATALOGO5)
  REFERENCES CATALOGO(IDCATALOGO);

ALTER TABLE ASEGURADORA ADD
  CONSTRAINT FKAUTOINVOLUCRADO3
  FOREIGN KEY (FKAUTOINVOLUCRADO3)
  REFERENCES AUTOINVOLUCRADO(IDAUTOINVOLUCRADO);



ALTER TABLE MARCAAUTO ADD
  CONSTRAINT IDMARCA
  PRIMARY KEY(IDMARCA);

ALTER TABLE MARCAAUTO ADD
  CONSTRAINT FKCATALOGO1
  FOREIGN KEY (FKCATALOGO1)
  REFERENCES CATALOGO(IDCATALOGO);

ALTER TABLE MARCAAUTO ADD
  CONSTRAINT FKCOTIZACION2
  FOREIGN KEY (FKCOTIZACION2)
  REFERENCES COTIZACION(IDCOTIZACION);

ALTER TABLE MARCAAUTO ADD
  CONSTRAINT FKTABULADOR2
  FOREIGN KEY (FKTABULADOR2)
  REFERENCES TABULADOR(IDTABULADOR);



ALTER TABLE MODELOAUTO ADD
  CONSTRAINT IDMODELOAUTO
  PRIMARY KEY(IDMODELOAUTO);

ALTER TABLE MODELOAUTO ADD
  CONSTRAINT FKCATALOGO2
  FOREIGN KEY (FKCATALOGO2)
  REFERENCES CATALOGO(IDCATALOGO);

ALTER TABLE MODELOAUTO ADD
  CONSTRAINT FKCOTIZACION3
  FOREIGN KEY (FKCOTIZACION3)
  REFERENCES COTIZACION(IDCOTIZACION);

ALTER TABLE MODELOAUTO ADD
  CONSTRAINT FKTABULADOR3
  FOREIGN KEY (FKTABULADOR3)
  REFERENCES TABULADOR(IDTABULADOR);



ALTER TABLE ESTADO ADD
  CONSTRAINT IDESTADO
  PRIMARY KEY(IDESTADO);

ALTER TABLE ESTADO ADD
  CONSTRAINT FKCATALOGO4
  FOREIGN KEY (FKCATALOGO4)
  REFERENCES CATALOGO(IDCATALOGO);

ALTER TABLE ESTADO ADD
  CONSTRAINT FKCOTIZACION6
  FOREIGN KEY (FKCOTIZACION6)
  REFERENCES COTIZACION(IDCOTIZACION);

ALTER TABLE ESTADO ADD
  CONSTRAINT FKTABULADOR5
  FOREIGN KEY (FKTABULADOR5)
  REFERENCES TABULADOR(IDTABULADOR);



ALTER TABLE TIPOSEGURO ADD
  CONSTRAINT IDTIPOSEGURO
  PRIMARY KEY(IDTIPOSEGURO);

ALTER TABLE TIPOSEGURO ADD
  CONSTRAINT FKCATALOGO3
  FOREIGN KEY (FKCATALOGO3)
  REFERENCES CATALOGO(IDCATALOGO);

ALTER TABLE TIPOSEGURO ADD
  CONSTRAINT FKCOTIZACION5
  FOREIGN KEY (FKCOTIZACION5)
  REFERENCES COTIZACION(IDCOTIZACION);

ALTER TABLE TIPOSEGURO ADD
  CONSTRAINT FKTABULADOR4
  FOREIGN KEY (FKTABULADOR4)
  REFERENCES TABULADOR(IDTABULADOR);



ALTER TABLE SINIESTRO ADD
  CONSTRAINT IDSINIESTRO
  PRIMARY KEY(IDSINIESTRO);

ALTER TABLE SINIESTRO ADD
  CONSTRAINT FKFOLIO4
  FOREIGN KEY (FKFOLIO4)
  REFERENCES POLIZA(FOLIO);

ALTER TABLE SINIESTRO ADD
  CONSTRAINT FKSOCIAL1
  FOREIGN KEY (FKSOCIAL1)
  REFERENCES SOCIAL(IDSOCIAL);

ALTER TABLE SINIESTRO ADD
  CONSTRAINT FKCOLISION1
  FOREIGN KEY (FKCOLISION1)
  REFERENCES COLISION(IDCOLISION);

ALTER TABLE SINIESTRO ADD
  CONSTRAINT FKMATERIAL1
  FOREIGN KEY (FKMATERIAL1)
  REFERENCES MATERIAL(IDMATERIAL);



ALTER TABLE COLISION ADD
  CONSTRAINT IDCOLISION
  PRIMARY KEY (IDCOLISION);

ALTER TABLE COLISION ADD
  CONSTRAINT FKSINIESTRO2
  FOREIGN KEY (FKSINIESTRO2)
  REFERENCES SINIESTRO(IDSINIESTRO);

ALTER TABLE COLISION ADD
  CONSTRAINT FKAUTOINVOLUCRADO1
  FOREIGN KEY (FKAUTOINVOLUCRADO1)
  REFERENCES AUTOINVOLUCRADO(IDAUTOINVOLUCRADO);



ALTER TABLE AUTOINVOLUCRADO ADD
  CONSTRAINT IDAUTOINVOLUCRADO
  PRIMARY KEY(IDAUTOINVOLUCRADO);  

ALTER TABLE AUTOINVOLUCRADO ADD
  CONSTRAINT FKASEGURADORA2
  FOREIGN KEY (FKASEGURADORA2)
  REFERENCES ASEGURADORA(IDASEGURADORA);

ALTER TABLE AUTOINVOLUCRADO ADD
  CONSTRAINT FKCOLISION2
  FOREIGN KEY (FKCOLISION2)
  REFERENCES COLISION(IDCOLISION);

ALTER TABLE AUTOINVOLUCRADO ADD
  CONSTRAINT FKMATERIAL3
  FOREIGN KEY (FKMATERIAL3)
  REFERENCES MATERIAL(IDMATERIAL);



ALTER TABLE MATERIAL ADD
  CONSTRAINT IDMATERIAL
  PRIMARY KEY (IDMATERIAL);

ALTER TABLE MATERIAL ADD
  CONSTRAINT FKSINIESTRO3
  FOREIGN KEY (FKSINIESTRO3)
  REFERENCES SINIESTRO(IDSINIESTRO);

ALTER TABLE MATERIAL ADD
  CONSTRAINT FKPERSONAAFECTADA2
  FOREIGN KEY(FKPERSONAAFECTADA2)
  REFERENCES PERSONAAFECTADA(IDPERSONAAFECTADA);

ALTER TABLE MATERIAL ADD
  CONSTRAINT FKAUTOINVOLUCRADO2
  FOREIGN KEY(FKAUTOINVOLUCRADO2)
  REFERENCES AUTOINVOLUCRADO (IDAUTOINVOLUCRADO);



ALTER TABLE SOCIAL ADD
  CONSTRAINT IDSOCIAL
  PRIMARY KEY (IDSOCIAL);

ALTER TABLE SOCIAL ADD
  CONSTRAINT FKSINIESTRO4
  FOREIGN KEY (FKSINIESTRO4)
  REFERENCES SINIESTRO (IDSINIESTRO);

ALTER TABLE SOCIAL ADD
  CONSTRAINT FKPERSONAAFECTADA1
  FOREIGN KEY(FKPERSONAAFECTADA1)
  REFERENCES PERSONAAFECTADA(IDPERSONAAFECTADA);



ALTER TABLE PERSONAAFECTADA ADD
  CONSTRAINT IDPERSONAAFECTADA
  PRIMARY KEY(IDPERSONAAFECTADA);

ALTER TABLE PERSONAAFECTADA ADD
  CONSTRAINT FKSOCIAL2
  FOREIGN KEY(FKSOCIAL2)
  REFERENCES SOCIAL(IDSOCIAL);

ALTER TABLE PERSONAAFECTADA ADD
  CONSTRAINT FKMATERIAL2
  FOREIGN KEY(FKMATERIAL2)
  REFERENCES MATERIAL(IDMATERIAL);