CREATE GLOBAL TEMPORARY TABLE SINIESTROTEMPORAL (
	IDSINIESTROTEMPORAL NUMBER(10,0) NOT NULL,
	FECHA DATE,
	HORA NUMBER(2,0),
	DIRECCION VARCHAR(50) NOT NULL,
	TIPOCOLISION CHAR(1) DEFAULT 'F' CHECK ((TIPOCOLISION = 'T') OR (TIPOCOLISION = 'F')) NOT NULL,
	TIPOMATERIAL CHAR(1) DEFAULT 'F' CHECK ((TIPOMATERIAL = 'T') OR (TIPOMATERIAL = 'F')) NOT NULL,
	TIPOSOCIAL CHAR(1) DEFAULT 'F' CHECK ((TIPOSOCIAL = 'T') OR (TIPOSOCIAL = 'F')) NOT NULL,
--  COLISION
	IDCOLISION NUMBER(10,0) NOT NULL,
	NUMEROREPORTEVIAL NUMBER(20,0),
	REQUIEREGRUA CHAR(1) DEFAULT 'F' CHECK ((REQUIEREGRUA = 'T') OR (REQUIEREGRUA = 'F')) NOT NULL,
--  MATERIAL
	IDMATERIAL NUMBER(10,0) NOT NULL,
	DESCRIPCION VARCHAR(200),
--  SOCIAL
	IDSOCIAL  NUMBER(10,0) NOT NULL,
	REQUIEREAMBULANCIA CHAR(1) DEFAULT 'F' CHECK ((REQUIEREAMBULANCIA = 'T') OR (REQUIEREAMBULANCIA = 'F')) NOT NULL,
	NOMBREHOSPITAL VARCHAR2(30)
) ON COMMIT DELETE ROWS;

INSERT INTO SINIESTROTEMPORAL
(IDSINIESTROTEMPORAL,FECHA,HORA,DIRECCION,TIPOCOLISION,TIPOMATERIAL,TIPOSOCIAL,
	IDCOLISION,NUMEROREPORTEVIAL,REQUIEREGRUA,
	IDMATERIAL,DESCRIPCION,
	IDSOCIAL,REQUIEREAMBULANCIA,NOMBREHOSPITAL)
VALUES (1,'18/01/2007',13,'Super Direccion','T','T','T',
	1,20,'T',
	1,'Super gacho',
	1,'T','Super Hospital');



CREATE GLOBAL TEMPORARY TABLE CARRITOCOMPRASTEMPORAL (
	IDCARRITOCOMPRASTEMPORAL NUMBER(10,0) NOT NULL,
	FKCOTIZACION NUMBER(10,0) NOT NULL,
	FKDUAL NUMBER(10,0) NOT NULL,
	COSTOANUAL NUMBER(7,3) NOT NULL,
	FKFOLIO NUMBER(10,0) NOT NULL,
	FKPAGOSEGURO NUMBER(10,0) NOT NULL
) ON COMMIT DELETE ROWS;

CREATE TABLE CARRITOCOMPRAS
AS (SELECT IDCARRITOCOMPRASTEMPORAL,FKCOTIZACION,FKDUAL,COSTOANUAL,FKFOLIO,FKPAGOSEGURO
	FROM CARRITOCOMPRASTEMPORAL);

INSERT INTO CARRITOCOMPRASTEMPORAL
(IDCARRITOCOMPRASTEMPORAL,FKCOTIZACION,FKDUAL,COSTOANUAL,FKFOLIO,FKPAGOSEGURO)
VALUES (1,23,23,1000,2325,40);

INSERT INTO CARRITOCOMPRAS
(IDCARRITOCOMPRASTEMPORAL,FKCOTIZACION,FKDUAL,COSTOANUAL,FKFOLIO,FKPAGOSEGURO)
VALUES (1,23,23,1000,2325,40);



CREATE TABLE COTIZACION1(
IDCOTIZACION NUMBER(10,0) NOT NULL, --primary key
FKTABULADOR1 NUMBER(10,0) NOT NULL,
FECHACOTIZACION DATE,
ANIOAUTO NUMBER(4,0),
CODIGOPOSTAL NUMBER(5,0),
EDADCONDUCTOR NUMBER(2,0),
FECHANACIMIENTO DATE
);
INSERT INTO COTIZACION1 VALUES(120,117,SYSDATE,2014,12345,20,SYSDATE);
--((SELECT IDCOTIZACION FROM COTIZACION1;)+(SELECT CODIGOPOSTAL FROM COTIZACION1;))
CREATE TABLE TABULADOR1(
IDTABULADOR NUMBER(10,0) NOT NULL,
FKCOTIZACION4 NUMBER(10,0) NOT NULL,
FKDUAL NUMBER(10,0) NOT NULL
);
INSERT INTO TABULADOR1 VALUES(117,120,117);
--((SELECT IDTABULADOR FROM TABULADOR1;)+(SELECT FKCOTIZACION4 FROM TABULADOR1;))
CREATE TABLE DUAL1(
IDDUAL NUMBER(10,0) NOT NULL,
FKTABULADOR6 NUMBER(10,0) NOT NULL,
COSTOANUAL NUMBER(7,3) NOT NULL
);
INSERT INTO DUAL1 VALUES(117,117,2000);
--((SELECT IDDUAL FROM DUAL;)+(SELECT FKTABULADOR6 FROM DUAL;))
--((SELECT IDDUAL FROM DUAL;)+(SELECT COSTOANUAL FROM DUAL;))

CREATE GLOBAL TEMPORARY TABLE VARIOSCALCULOSDINEROTEMPORAL (
	IDVARIOSCALCULOSDINEROTEMPORAL NUMBER(10,0) NOT NULL,
	FKCOTIZACION NUMBER(10,0) NOT NULL,
	FKTABULADOR NUMBER(10,0) NOT NULL,
	FKDUAL NUMBER(10,0) NOT NULL,
	COSTOANUAL NUMBER(7,3) NOT NULL
) ON COMMIT DELETE ROWS;

INSERT INTO VARIOSCALCULOSDINEROTEMPORAL VALUES
(1,
((SELECT IDCOTIZACION FROM COTIZACION1)+(SELECT CODIGOPOSTAL FROM COTIZACION1)),
((SELECT IDTABULADOR FROM TABULADOR1)+(SELECT FKCOTIZACION4 FROM TABULADOR1)),
((SELECT IDDUAL FROM DUAL1)+(SELECT FKTABULADOR6 FROM DUAL1)),
((SELECT IDDUAL FROM DUAL1)+(SELECT COSTOANUAL FROM DUAL1)));