--Sentencias CREATE SEQUENCE

--CREATE SEQUENCE <Nombre_SEQ>
--	START WITH n --En donde comienza
--	INCREMENT BY 1 --De cuanto en cuanto va a Incrementar
--	[MINVALUE n /*Valor Menor*/ | NOMINVALUE /*Negación de Limite del Valor Menor*/]
--	[MAXVALUE n /*Valor Maximo*/ | NOMAXVALUE /*Negación de Limite del Valor Maximo*/]
--	[CYCLE /*Cuando llegue al limite, resetea su valor al menor*/ | NOCYCLE /*Negacion de Cycle*/]
--	CACHE 20
--	NOORDER
--;

--DROP SEQUENCE <Nombre_SEQ>

CREATE SEQUENCE CLIENTE_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE COTIZACION_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE TABULADOR_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE DUAL_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE POLIZA_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE PAGOSEGURO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE CATALOGO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE ASEGURADORA_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE MARCAAUTO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE MODELOAUTO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE ESTADO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE TIPOSEGURO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE SINIESTRO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE COLISION_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE AUTOINVOLUCRADO_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE MATERIAL_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE SOCIAL_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;

CREATE SEQUENCE PERSONAAFECTADA_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1;