--Sentencias INSERT INTO

/*
	.NEXTVAL
	.CURRVAL

	CLIENTE_SEQ
	COTIZACION_SEQ
	TABULADOR_SEQ
	DUAL_SEQ
	POLIZA_SEQ
	PAGOSEGURO_SEQ
	CATALOGO_SEQ
	ASEGURADORA_SEQ
	MARCAAUTO_SEQ
	MODELOAUTO_SEQ
	ESTADO_SEQ
	TIPOSEGURO_SEQ
	SINIESTRO_SEQ
	COLISION_SEQ
	AUTOINVOLUCRADO_SEQ
	MATERIAL_SEQ
	SOCIAL_SEQ
	PERSONAAFECTADA_SEQ

	COSTOANUAL=(FKTABULADOR6*1000)
*/

--	1eros Registros

INSERT INTO CLIENTE
VALUES(CLIENTE_SEQ.NEXTVAL,COTIZACION_SEQ.NEXTVAL,POLIZA_SEQ.NEXTVAL,
'Pepe','Gonzales','Perez','fake@email.com','rfc1','dir1',12345678);

INSERT INTO COTIZACION
VALUES(COTIZACION_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,
MARCAAUTO_SEQ.NEXTVAL,MODELOAUTO_SEQ.NEXTVAL,TIPOSEGURO_SEQ.NEXTVAL,
ESTADO_SEQ.NEXTVAL,TABULADOR_SEQ.NEXTVAL,SYSDATE,2000,12345,20,SYSDATE);

INSERT INTO TABULADOR
VALUES(TABULADOR_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,MARCAAUTO_SEQ.CURRVAL,
MODELOAUTO_SEQ.CURRVAL,TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,
DUAL_SEQ.NEXTVAL);

INSERT INTO DUAL
VALUES(DUAL_SEQ.NEXTVAL,TABULADOR_SEQ.CURRVAL,
(TABULADOR_SEQ.CURRVAL*1000));

INSERT INTO POLIZA
VALUES(POLIZA_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,null,COTIZACION_SEQ.CURRVAL,
PAGOSEGURO_SEQ.NEXTVAL,SINIESTRO_SEQ.NEXTVAL,SYSDATE,13,SYSDATE,
'0123456789',335);

INSERT INTO PAGOSEGURO
VALUES(PAGOSEGURO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,7845,'Standar','Febrero',
2005,312);

INSERT INTO CATALOGO
VALUES(CATALOGO_SEQ.NEXTVAL,MARCAAUTO_SEQ.CURRVAL,MODELOAUTO_SEQ.CURRVAL,
TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,ASEGURADORA_SEQ.NEXTVAL);

INSERT INTO ASEGURADORA
VALUES(ASEGURADORA_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.NEXTVAL,null);

INSERT INTO MARCAAUTO
VALUES(MARCAAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO MODELOAUTO
VALUES(MODELOAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO ESTADO
VALUES(ESTADO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.NEXTVAL,
TABULADOR_SEQ.CURRVAL,'Ciudad de Mexico');

INSERT INTO TIPOSEGURO_SEQ
VALUES(TIPOSEGURO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO SINIESTRO
VALUES(SINIESTRO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,SOCIAL_SEQ.NEXTVAL,
COLISION_SEQ.NEXTVAL,MATERIAL_SEQ.NEXTVAL,SYSDATE,17,'dir2','T','T','T',null);

INSERT INTO COLISION
VALUES(COTIZACION_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.CURRVAL,5446,'T');

INSERT INTO AUTOINVOLUCRADO
VALUES(AUTOINVOLUCRADO_SEQ.CURRVAL,ASEGURADORA_SEQ.CURRVAL,
COLISION_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,'SuperMarca','SuperModelo',2453,
2645);

INSERT INTO MATERIAL
VALUES(MATERIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
PERSONAAFECTADA_SEQ.NEXTVAL,AUTOINVOLUCRADO_SEQ.CURRVAL,null,null);

INSERT INTO SOCIAL
VALUES(SOCIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,PERSONAAFECTADA_SEQ.CURRVAL,
'T','SuperHospital','dir3');

INSERT INTO PERSONAAFECTADA
VALUES(PERSONAAFECTADA_SEQ.CURRVAL,SOCIAL_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,
'Jose Gonzales','FYT678V7',null);


--	2dos Registros

INSERT INTO CLIENTE
VALUES(CLIENTE_SEQ.NEXTVAL,COTIZACION_SEQ.NEXTVAL,POLIZA_SEQ.NEXTVAL,
'Luis','Rojas','Garcia','fake2@email.com','rfc2','dir4',5676548);

INSERT INTO COTIZACION
VALUES(COTIZACION_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,
MARCAAUTO_SEQ.NEXTVAL,MODELOAUTO_SEQ.NEXTVAL,TIPOSEGURO_SEQ.NEXTVAL,
ESTADO_SEQ.NEXTVAL,TABULADOR_SEQ.NEXTVAL,SYSDATE,2011,24680,30,SYSDATE);

INSERT INTO TABULADOR
VALUES(TABULADOR_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,MARCAAUTO_SEQ.CURRVAL,
MODELOAUTO_SEQ.CURRVAL,TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,
DUAL_SEQ.NEXTVAL);

INSERT INTO DUAL
VALUES(DUAL_SEQ.NEXTVAL,TABULADOR_SEQ.CURRVAL,
(TABULADOR_SEQ.CURRVAL*1000));

INSERT INTO POLIZA
VALUES(POLIZA_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,null,COTIZACION_SEQ.CURRVAL,
PAGOSEGURO_SEQ.NEXTVAL,SINIESTRO_SEQ.NEXTVAL,SYSDATE,13,SYSDATE,
'46565967',54678687);

INSERT INTO PAGOSEGURO
VALUES(PAGOSEGURO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,7845,'Standar','Junio',
2005,312);

INSERT INTO CATALOGO
VALUES(CATALOGO_SEQ.NEXTVAL,MARCAAUTO_SEQ.CURRVAL,MODELOAUTO_SEQ.CURRVAL,
TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,ASEGURADORA_SEQ.NEXTVAL);

INSERT INTO ASEGURADORA
VALUES(ASEGURADORA_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.NEXTVAL,null);

INSERT INTO MARCAAUTO
VALUES(MARCAAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO MODELOAUTO
VALUES(MODELOAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO ESTADO
VALUES(ESTADO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.NEXTVAL,
TABULADOR_SEQ.CURRVAL,'Ciudad de Mexico');

INSERT INTO TIPOSEGURO_SEQ
VALUES(TIPOSEGURO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO SINIESTRO
VALUES(SINIESTRO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,SOCIAL_SEQ.NEXTVAL,
COLISION_SEQ.NEXTVAL,MATERIAL_SEQ.NEXTVAL,SYSDATE,11,'dir5','T','T','T',null);

INSERT INTO COLISION
VALUES(COTIZACION_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.CURRVAL,479878,'T');

INSERT INTO AUTOINVOLUCRADO
VALUES(AUTOINVOLUCRADO_SEQ.CURRVAL,ASEGURADORA_SEQ.CURRVAL,
COLISION_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,'SuperMarca2','SuperModelo2',545676,
55776);

INSERT INTO MATERIAL
VALUES(MATERIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
PERSONAAFECTADA_SEQ.NEXTVAL,AUTOINVOLUCRADO_SEQ.CURRVAL,null,null);

INSERT INTO SOCIAL
VALUES(SOCIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,PERSONAAFECTADA_SEQ.CURRVAL,
'T','SuperHospital2','dir6');

INSERT INTO PERSONAAFECTADA
VALUES(PERSONAAFECTADA_SEQ.CURRVAL,SOCIAL_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,
'Felipe Castillo','G76HGIH8N',null);


--	3eros Registros

INSERT INTO CLIENTE
VALUES(CLIENTE_SEQ.NEXTVAL,COTIZACION_SEQ.NEXTVAL,POLIZA_SEQ.NEXTVAL,
'Leonardo','Barcenas','Aguilar','fake3@email.com','rfc3','dir7',536345);

INSERT INTO COTIZACION
VALUES(COTIZACION_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,
MARCAAUTO_SEQ.NEXTVAL,MODELOAUTO_SEQ.NEXTVAL,TIPOSEGURO_SEQ.NEXTVAL,
ESTADO_SEQ.NEXTVAL,TABULADOR_SEQ.NEXTVAL,SYSDATE,2005,56673,35,SYSDATE);

INSERT INTO TABULADOR
VALUES(TABULADOR_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,MARCAAUTO_SEQ.CURRVAL,
MODELOAUTO_SEQ.CURRVAL,TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,
DUAL_SEQ.NEXTVAL);

INSERT INTO DUAL
VALUES(DUAL_SEQ.NEXTVAL,TABULADOR_SEQ.CURRVAL,
(TABULADOR_SEQ.CURRVAL*1000));

INSERT INTO POLIZA
VALUES(POLIZA_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,null,COTIZACION_SEQ.CURRVAL,
PAGOSEGURO_SEQ.NEXTVAL,SINIESTRO_SEQ.NEXTVAL,SYSDATE,10,SYSDATE,
'345667',4767849);

INSERT INTO PAGOSEGURO
VALUES(PAGOSEGURO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,7845,'Premium','Abril',
2020,735);

INSERT INTO CATALOGO
VALUES(CATALOGO_SEQ.NEXTVAL,MARCAAUTO_SEQ.CURRVAL,MODELOAUTO_SEQ.CURRVAL,
TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,ASEGURADORA_SEQ.NEXTVAL);

INSERT INTO ASEGURADORA
VALUES(ASEGURADORA_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.NEXTVAL,null);

INSERT INTO MARCAAUTO
VALUES(MARCAAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO MODELOAUTO
VALUES(MODELOAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO ESTADO
VALUES(ESTADO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.NEXTVAL,
TABULADOR_SEQ.CURRVAL,'Ciudad de Mexico');

INSERT INTO TIPOSEGURO_SEQ
VALUES(TIPOSEGURO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO SINIESTRO
VALUES(SINIESTRO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,SOCIAL_SEQ.NEXTVAL,
COLISION_SEQ.NEXTVAL,MATERIAL_SEQ.NEXTVAL,SYSDATE,11,'dir8','T','T','T',null);

INSERT INTO COLISION
VALUES(COTIZACION_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.CURRVAL,55354,'T');

INSERT INTO AUTOINVOLUCRADO
VALUES(AUTOINVOLUCRADO_SEQ.CURRVAL,ASEGURADORA_SEQ.CURRVAL,
COLISION_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,'SuperMarca3','SuperModelo3',545676,
55776);

INSERT INTO MATERIAL
VALUES(MATERIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
PERSONAAFECTADA_SEQ.NEXTVAL,AUTOINVOLUCRADO_SEQ.CURRVAL,null,null);

INSERT INTO SOCIAL
VALUES(SOCIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,PERSONAAFECTADA_SEQ.CURRVAL,
'T','SuperHospital3','dir9');

INSERT INTO PERSONAAFECTADA
VALUES(PERSONAAFECTADA_SEQ.CURRVAL,SOCIAL_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,
'Jovany Carrera','HU7Y8H8Y',null);


--	4tos Registros

INSERT INTO CLIENTE
VALUES(CLIENTE_SEQ.NEXTVAL,COTIZACION_SEQ.NEXTVAL,POLIZA_SEQ.NEXTVAL,
'Ericka','Flores','Cruz','fake4@email.com','rfc4','dir10',7324646);

INSERT INTO COTIZACION
VALUES(COTIZACION_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,
MARCAAUTO_SEQ.NEXTVAL,MODELOAUTO_SEQ.NEXTVAL,TIPOSEGURO_SEQ.NEXTVAL,
ESTADO_SEQ.NEXTVAL,TABULADOR_SEQ.NEXTVAL,SYSDATE,2011,25364,20,SYSDATE);

INSERT INTO TABULADOR
VALUES(TABULADOR_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,MARCAAUTO_SEQ.CURRVAL,
MODELOAUTO_SEQ.CURRVAL,TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,
DUAL_SEQ.NEXTVAL);

INSERT INTO DUAL
VALUES(DUAL_SEQ.NEXTVAL,TABULADOR_SEQ.CURRVAL,
(TABULADOR_SEQ.CURRVAL*1000));

INSERT INTO POLIZA
VALUES(POLIZA_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,null,COTIZACION_SEQ.CURRVAL,
PAGOSEGURO_SEQ.NEXTVAL,SINIESTRO_SEQ.NEXTVAL,SYSDATE,19,SYSDATE,
'0886676',64445434);

INSERT INTO PAGOSEGURO
VALUES(PAGOSEGURO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,7845,'Premium','Septiembre',
2005,312);

INSERT INTO CATALOGO
VALUES(CATALOGO_SEQ.NEXTVAL,MARCAAUTO_SEQ.CURRVAL,MODELOAUTO_SEQ.CURRVAL,
TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,ASEGURADORA_SEQ.NEXTVAL);

INSERT INTO ASEGURADORA
VALUES(ASEGURADORA_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.NEXTVAL,null);

INSERT INTO MARCAAUTO
VALUES(MARCAAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO MODELOAUTO
VALUES(MODELOAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO ESTADO
VALUES(ESTADO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.NEXTVAL,
TABULADOR_SEQ.CURRVAL,'Ciudad de Mexico');

INSERT INTO TIPOSEGURO_SEQ
VALUES(TIPOSEGURO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO SINIESTRO
VALUES(SINIESTRO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,SOCIAL_SEQ.NEXTVAL,
COLISION_SEQ.NEXTVAL,MATERIAL_SEQ.NEXTVAL,SYSDATE,20,'dir11','T','T','T',null);

INSERT INTO COLISION
VALUES(COTIZACION_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.CURRVAL,54678,'T');

INSERT INTO AUTOINVOLUCRADO
VALUES(AUTOINVOLUCRADO_SEQ.CURRVAL,ASEGURADORA_SEQ.CURRVAL,
COLISION_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,'SuperMarca4','SuperModelo4',545676,
55776);

INSERT INTO MATERIAL
VALUES(MATERIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
PERSONAAFECTADA_SEQ.NEXTVAL,AUTOINVOLUCRADO_SEQ.CURRVAL,null,null);

INSERT INTO SOCIAL
VALUES(SOCIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,PERSONAAFECTADA_SEQ.CURRVAL,
'T','SuperHospital4','dir12');

INSERT INTO PERSONAAFECTADA
VALUES(PERSONAAFECTADA_SEQ.CURRVAL,SOCIAL_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,
'Mariana Ladino','GVUB87886',null);


--	5tos Registros

INSERT INTO CLIENTE
VALUES(CLIENTE_SEQ.NEXTVAL,COTIZACION_SEQ.NEXTVAL,POLIZA_SEQ.NEXTVAL,
'Yazemin','Avendano','Flores','fake5@email.com','rfc5','dir13',7324646);

INSERT INTO COTIZACION
VALUES(COTIZACION_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,
MARCAAUTO_SEQ.NEXTVAL,MODELOAUTO_SEQ.NEXTVAL,TIPOSEGURO_SEQ.NEXTVAL,
ESTADO_SEQ.NEXTVAL,TABULADOR_SEQ.NEXTVAL,SYSDATE,2013,38954,18,SYSDATE);

INSERT INTO TABULADOR
VALUES(TABULADOR_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,MARCAAUTO_SEQ.CURRVAL,
MODELOAUTO_SEQ.CURRVAL,TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,
DUAL_SEQ.NEXTVAL);

INSERT INTO DUAL
VALUES(DUAL_SEQ.NEXTVAL,TABULADOR_SEQ.CURRVAL,
(TABULADOR_SEQ.CURRVAL*1000));

INSERT INTO POLIZA
VALUES(POLIZA_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,null,COTIZACION_SEQ.CURRVAL,
PAGOSEGURO_SEQ.NEXTVAL,SINIESTRO_SEQ.NEXTVAL,SYSDATE,20,SYSDATE,
'0886676',64445434);

INSERT INTO PAGOSEGURO
VALUES(PAGOSEGURO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,7845,'Premium','Enero',
2005,312);

INSERT INTO CATALOGO
VALUES(CATALOGO_SEQ.NEXTVAL,MARCAAUTO_SEQ.CURRVAL,MODELOAUTO_SEQ.CURRVAL,
TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,ASEGURADORA_SEQ.NEXTVAL);

INSERT INTO ASEGURADORA
VALUES(ASEGURADORA_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.NEXTVAL,null);

INSERT INTO MARCAAUTO
VALUES(MARCAAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO MODELOAUTO
VALUES(MODELOAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO ESTADO
VALUES(ESTADO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.NEXTVAL,
TABULADOR_SEQ.CURRVAL,'Ciudad de Mexico');

INSERT INTO TIPOSEGURO_SEQ
VALUES(TIPOSEGURO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO SINIESTRO
VALUES(SINIESTRO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,SOCIAL_SEQ.NEXTVAL,
COLISION_SEQ.NEXTVAL,MATERIAL_SEQ.NEXTVAL,SYSDATE,20,'dir14','T','T','T',null);

INSERT INTO COLISION
VALUES(COTIZACION_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.CURRVAL,23573,'T');

INSERT INTO AUTOINVOLUCRADO
VALUES(AUTOINVOLUCRADO_SEQ.CURRVAL,ASEGURADORA_SEQ.CURRVAL,
COLISION_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,'SuperMarca5','SuperModelo5',932232,
55376);

INSERT INTO MATERIAL
VALUES(MATERIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
PERSONAAFECTADA_SEQ.NEXTVAL,AUTOINVOLUCRADO_SEQ.CURRVAL,null,null);

INSERT INTO SOCIAL
VALUES(SOCIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,PERSONAAFECTADA_SEQ.CURRVAL,
'T','SuperHospital5','dir15');

INSERT INTO PERSONAAFECTADA
VALUES(PERSONAAFECTADA_SEQ.CURRVAL,SOCIAL_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,
'Sara Gbh','Sbyiub3',null);


--	6tos Registros

INSERT INTO CLIENTE
VALUES(CLIENTE_SEQ.NEXTVAL,COTIZACION_SEQ.NEXTVAL,POLIZA_SEQ.NEXTVAL,
'Pepe6','Gonzales6','Fernande6','fake6@email.com','rfc6','dir16',7324646);

INSERT INTO COTIZACION
VALUES(COTIZACION_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,
MARCAAUTO_SEQ.NEXTVAL,MODELOAUTO_SEQ.NEXTVAL,TIPOSEGURO_SEQ.NEXTVAL,
ESTADO_SEQ.NEXTVAL,TABULADOR_SEQ.NEXTVAL,SYSDATE,2001,56789,40,SYSDATE);

INSERT INTO TABULADOR
VALUES(TABULADOR_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,MARCAAUTO_SEQ.CURRVAL,
MODELOAUTO_SEQ.CURRVAL,TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,
DUAL_SEQ.NEXTVAL);

INSERT INTO DUAL
VALUES(DUAL_SEQ.NEXTVAL,TABULADOR_SEQ.CURRVAL,
(TABULADOR_SEQ.CURRVAL*1000));

INSERT INTO POLIZA
VALUES(POLIZA_SEQ.CURRVAL,CLIENTE_SEQ.CURRVAL,null,COTIZACION_SEQ.CURRVAL,
PAGOSEGURO_SEQ.NEXTVAL,SINIESTRO_SEQ.NEXTVAL,SYSDATE,18,SYSDATE,
'5678767',34954576);

INSERT INTO PAGOSEGURO
VALUES(PAGOSEGURO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,7845,'Standar','Diciembre',
2015,843);

INSERT INTO CATALOGO
VALUES(CATALOGO_SEQ.NEXTVAL,MARCAAUTO_SEQ.CURRVAL,MODELOAUTO_SEQ.CURRVAL,
TIPOSEGURO_SEQ.CURRVAL,ESTADO_SEQ.CURRVAL,ASEGURADORA_SEQ.NEXTVAL);

INSERT INTO ASEGURADORA
VALUES(ASEGURADORA_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.NEXTVAL,null);

INSERT INTO MARCAAUTO
VALUES(MARCAAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO MODELOAUTO
VALUES(MODELOAUTO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO ESTADO
VALUES(ESTADO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.NEXTVAL,
TABULADOR_SEQ.CURRVAL,'Ciudad de Mexico');

INSERT INTO TIPOSEGURO_SEQ
VALUES(TIPOSEGURO_SEQ.CURRVAL,CATALOGO_SEQ.CURRVAL,COTIZACION_SEQ.CURRVAL,
TABULADOR_SEQ.CURRVAL,null);

INSERT INTO SINIESTRO
VALUES(SINIESTRO_SEQ.CURRVAL,POLIZA_SEQ.CURRVAL,SOCIAL_SEQ.NEXTVAL,
COLISION_SEQ.NEXTVAL,MATERIAL_SEQ.NEXTVAL,SYSDATE,21,'dir16','T','T','T',null);

INSERT INTO COLISION
VALUES(COTIZACION_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
AUTOINVOLUCRADO_SEQ.CURRVAL,73436,'T');

INSERT INTO AUTOINVOLUCRADO
VALUES(AUTOINVOLUCRADO_SEQ.CURRVAL,ASEGURADORA_SEQ.CURRVAL,
COLISION_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,'SuperMarca6','SuperModelo6',972232,
74646);

INSERT INTO MATERIAL
VALUES(MATERIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,
PERSONAAFECTADA_SEQ.NEXTVAL,AUTOINVOLUCRADO_SEQ.CURRVAL,null,null);

INSERT INTO SOCIAL
VALUES(SOCIAL_SEQ.CURRVAL,SINIESTRO_SEQ.CURRVAL,PERSONAAFECTADA_SEQ.CURRVAL,
'T','SuperHospital6','dir17');

INSERT INTO PERSONAAFECTADA
VALUES(PERSONAAFECTADA_SEQ.CURRVAL,SOCIAL_SEQ.CURRVAL,MATERIAL_SEQ.CURRVAL,
'Sara Gbh','Sbyiub3',null);